<?php
namespace app\admin\route;

use think\facade\Route;

Route::rule('login','index/login');
Route::rule('getlogininfo','index/getlogininfo');
Route::rule('mainpage','index/mainpage');
Route::rule('createNewGame','index/createNewGame');
Route::rule('queryPlayerCount','index/queryPlayerCount');
Route::rule('confirmIdentity','index/confirmIdentity');
Route::rule('confirmVote','index/confirmVote');
Route::rule('gameStart','index/gameStart');
Route::rule('voteTimeSet','index/voteTimeSet');
Route::rule('queryVoteTimeSetting','index/queryVoteTimeSetting');
Route::rule('endGame','index/endGame');
Route::rule('queryGameLiveData','index/queryGameLiveData');
Route::rule('startVote','index/startVote');
Route::rule('endVote','index/endVote');
Route::rule('queryJoinGameData','index/queryJoinGameData');
Route::rule('getAllPlayerInfo','index/getAllPlayerInfo');
Route::rule('queryWinnerScore','index/queryWinnerScore');
Route::rule('updateWinnerScore','index/updateWinnerScore');
Route::rule('hidePlayer','index/hidePlayer');
Route::rule('passPlayerJoinGame','index/passPlayerJoinGame');
Route::rule('refusePlayerJoinGame','index/refusePlayerJoinGame');
Route::rule('queryReviewedData','index/queryReviewedData');
Route::rule('queryJoinPlayer','index/queryJoinPlayer');
Route::rule('queryPlayerSkill','index/queryPlayerSkill');
Route::rule('allowUseSkill','index/allowUseSkill');
Route::rule('disAllowUseSkill','index/disAllowUseSkill');
Route::rule('sendZhongliRoles','index/sendZhongliRoles');
Route::rule('sap','index/settleAccountsPage');
Route::rule('sendAllUsers','index/sendAllUsers');
Route::rule('updateTargetUser','index/updateTargetUser');
Route::rule('sendAllBill','index/sendAllBill');
Route::rule('sendTargetBill','index/sendTargetBill');
Route::rule('playerSettleAccount','index/playerSettleAccount');
Route::rule('batchSettleAccount','index/batchSettleAccount');
Route::rule('updatePrice','index/updatePrice');
Route::rule('updateSaTime','index/updateSaTime');
Route::rule('batchSetRemainderZero','index/batchSetRemainderZero');
Route::rule('deleteTwoYearsAgoBill','index/deleteTwoYearsAgoBill');